In [4]:
import torch
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [5]:
class_features = torch.load("assets/class_features.pt")

with open("assets/class_labels.txt") as f:
    class_labels = f.read().splitlines()

In [6]:
fp16_image_features = np.load("assets/fp16_image_features.npy")
fp32_image_features = np.load("assets/fp32_image_features.npy")
int8_image_features = np.load("assets/int8_image_features.npy")

In [8]:
fp32_image_features[0, :10], fp32_image_features[1, :10], fp32_image_features[2, :10]

(array([ 0.00266622, -0.02397259,  0.07347347, -0.02166717, -0.01637221,
        -0.03255699,  0.02222947,  0.02119859, -0.03176978,  0.00055761],
       dtype=float32),
 array([ 0.0257829 ,  0.01132223, -0.00938553,  0.03748254,  0.00144507,
        -0.04421628,  0.05013562, -0.0017182 , -0.05414806,  0.04091893],
       dtype=float32),
 array([ 0.00481593,  0.0131218 , -0.0274591 , -0.00591632,  0.03156599,
         0.00807566,  0.00329657, -0.0095582 , -0.01559883,  0.0333524 ],
       dtype=float32))

In [9]:
text_probs = (100.0 * fp32_image_features @ class_features.T).softmax(dim=-1)
top_probs, top_labels = text_probs.cpu().topk(5, dim=-1)

TypeError: unsupported operand type(s) for @: 'numpy.ndarray' and 'Tensor'

In [ ]:
plt.figure(figsize=(16, 16))

for i, image in enumerate(original_images):
    plt.subplot(4, 4, 2 * i + 1)
    plt.imshow(image)
    plt.axis("off")

    plt.subplot(4, 4, 2 * i + 2)
    y = np.arange(top_probs.shape[-1])
    plt.grid()
    plt.barh(y, top_probs[i])
    plt.gca().invert_yaxis()
    plt.gca().set_axisbelow(True)
    plt.yticks(y, [class_labels[index] for index in top_labels[i].numpy()])
    plt.xlabel("probability")

plt.subplots_adjust(wspace=0.5)
plt.show()
